version: '3.8'
services:
  frontapp:
    image: frontapp
    environment:
      - BACK_URL=http://backapp:8081
    ports:
      - "8083:8080"  # A frontapp elérhetővé tétele a host gépen
    depends_on:
      - backapp

  backapp:
    image: backapp
    environment:
      - APP_DEFAULT_MESSAGE=""
    networks:
      - internal
    ports:
      - "8081:8080" 

networks:
  internal:
    driver: bridge
