version: '3.8'
services:
  frontapp:
    image: frontapp
    environment:
      - BACK_URL=http://backapp:8080
    ports:
      - "8083:8080"

  backapp:
    image: backapp
    ports:
      - "8081:8080" 
